--DDL FILE

-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-12-10 00:10:49 GMT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE booking CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE party CASCADE CONSTRAINTS;

DROP TABLE restaurants CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

DROP TABLE "Table" CASCADE CONSTRAINTS;

DROP VIEW party_book_4;

DROP VIEW booking_receipt;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE booking (
    bookingid    NUMBER(7) NOT NULL,
    bookingtype  VARCHAR2(30) NOT NULL,
    time_from    TIMESTAMP NOT NULL,
    time_to      TIMESTAMP NOT NULL,
    no_of_people NUMBER(10) NOT NULL,
    amount       NUMBER(9, 2) NOT NULL,
    penalty      NUMBER(9, 2) NOT NULL,
    custid       NUMBER(7) NOT NULL,
    tableid      NUMBER(7) NOT NULL,
    managerid    NUMBER(7) NOT NULL,
    waiterid     NUMBER(7) NOT NULL
);

ALTER TABLE booking ADD CONSTRAINT booking_ppl_ck_1 CHECK ( no_of_people <= 6 );

ALTER TABLE booking ADD CONSTRAINT booking_pk PRIMARY KEY ( bookingid );

CREATE TABLE customer (
    custid  NUMBER(7) NOT NULL,
    name    VARCHAR2(30) NOT NULL,
    email   VARCHAR2(30) NOT NULL,
    address VARCHAR2(50) NOT NULL,
    age     NUMBER(3) NOT NULL,
    phone   NUMBER(10) NOT NULL
);

ALTER TABLE customer ADD CONSTRAINT customer_age_ck_1 CHECK ( age >= 18 );

ALTER TABLE customer ADD CONSTRAINT customer_email_ck_2 CHECK ( email LIKE '%@%' );

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( custid );

CREATE TABLE party (
    partyid   NUMBER(7) NOT NULL,
    name      VARCHAR2(30) NOT NULL,
    email     VARCHAR2(30) NOT NULL,
    address   VARCHAR2(50) NOT NULL,
    phone     NUMBER(10) NOT NULL,
    bookingid NUMBER(7) NOT NULL
);

ALTER TABLE party ADD CONSTRAINT party_email_ck_1 CHECK ( email LIKE '%@%' );

ALTER TABLE party ADD CONSTRAINT party_pk PRIMARY KEY ( partyid );

CREATE TABLE restaurants (
    restaurantid NUMBER(7) NOT NULL,
    address      VARCHAR2(50) NOT NULL,
    phone        NUMBER(10) NOT NULL
);

ALTER TABLE restaurants ADD CONSTRAINT restaurants_pk PRIMARY KEY ( restaurantid );

CREATE TABLE staff (
    staffid      NUMBER(7) NOT NULL,
    name         VARCHAR2(30) NOT NULL,
    address      VARCHAR2(50) NOT NULL,
    phone        NUMBER(10) NOT NULL,
    email        VARCHAR2(30) NOT NULL,
    dob          DATE NOT NULL,
    staffpost    VARCHAR2(30) NOT NULL,
    start_date   DATE NOT NULL,
    restaurantid NUMBER(7) NOT NULL
);

ALTER TABLE staff ADD CONSTRAINT staff_ck_1 CHECK ( email LIKE '%@burgershack.com' );

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staffid );

CREATE TABLE "Table" (
    tableid  NUMBER(7) NOT NULL,
    type     NUMBER(7) NOT NULL,
    location VARCHAR2(10) NOT NULL
);

ALTER TABLE "Table" ADD CONSTRAINT table_pk PRIMARY KEY ( tableid );

ALTER TABLE booking
    ADD CONSTRAINT booking_customer_fk FOREIGN KEY ( custid )
        REFERENCES customer ( custid );

ALTER TABLE booking
    ADD CONSTRAINT booking_staff_fk FOREIGN KEY ( waiterid )
        REFERENCES staff ( staffid );

ALTER TABLE booking
    ADD CONSTRAINT booking_staff_fkv2 FOREIGN KEY ( managerid )
        REFERENCES staff ( staffid );

ALTER TABLE booking
    ADD CONSTRAINT booking_table_fk FOREIGN KEY ( tableid )
        REFERENCES "Table" ( tableid );

ALTER TABLE party
    ADD CONSTRAINT party_booking_fk FOREIGN KEY ( bookingid )
        REFERENCES booking ( bookingid );

ALTER TABLE staff
    ADD CONSTRAINT staff_restaurants_fk FOREIGN KEY ( restaurantid )
        REFERENCES restaurants ( restaurantid );

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
